import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";

const CreatePostWizard = () => {
  const {user} = useUser();

  if (!user) return null;

  return (
  <div className="flex gap-3 w-full">
    <img 
      src={user.profileImageUrl} 
      alt="Profile image"
      className="h-16 w-16 rounded-full"
    />
    <input placeholder="type some emojis" className="bg-transparent grow outline-none"/>
  </div>
  );
}

export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div> Loading... </div>

  if (!data) return <div> Something went wrong </div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-4 flex">
            {!user.isSignedIn && (
              <div className="flex justify-center">
               <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard/>}
          </div>

          <div className="flex flex-col">
            {[...data, ...data].map((post) => (
              <div key={post.id} className="p-8 border-b border-slate-400">{post.content}</div>
              ))}
          </div>
        </div>
          
      </main>
    </>
  );
}
